{% set name = "duckdb-server" %}
{% set version = "0.17.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/duckdb_server-{{ version }}.tar.gz
  sha256: a43883f75fbbc5a6dcd4e5f9c25fa91697c1d490021fb4f60b1e92afc3743ef1

build:
  entry_points:
    - duckdb-server = pkg.__main__:serve
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - diskcache
    - python-duckdb >=1.1.3
    - pandas
    - pyarrow
    - socketify
    - ujson

test:
  imports:
    - duckdb
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/uwdata/mosaic/tree/main/packages/duckdb-server
  summary: A DuckDB server for Mosaic
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
